---
- name: Ensure zsh is installed
  apt:
    name: zsh
    state: latest

- name: Change root default shell to zsh
  user:
    name: root
    shell: /usr/bin/zsh

- name: Change {{ ansible_user }} default shell to zsh
  user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh

- name: Clone oh-my-zsh git project for root
  command: "git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh"

- name: Clone oh-my-zsh git project for {{ ansible_user }}
  command: "git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh"
  become: yes
  become_user: ansible_user

- name: Create new zsh configuration file for root
  copy:
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc

- name: Create new zsh configuration file for root
  copy:
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc
  become: yes
  become_user: ansible_user



- name: Change prompt color
  lineinfile:
    path: "/home/{{ ansible_user }}/.oh-my-zsh/themes/robbyrussell.zsh-theme"
    regexp: '^PROMPT'
    line: "PROMPT='%{$fg_bold[black]%}%M ${ret_status} %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)'"